#
# Makefile for Algorithms Paradigms project
#
# author: Gustavo Pantuza
# since: 26.04.2013
#


# Latex dir
TEX_PATH := doc


all:
	@echo "What's up, doc!"

clean:
	rm -vf ${TEX_PATH}/{*.dvi,*.aux,*.log,*.pdf}
